import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import List from './components/list'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import {useState} from 'react'

const fetcher = (...args: any) => fetch(...args).then(res => res.json())

const Home: NextPage = () => {
  const [ address, setAddress ] = useState('http://localhost:8080/')
  const { data, error } = useSWR(address, fetcher)
  let datas;
  {if(data){
    datas = data.map((value: any,key: any)=>(
      <li key={key} value={key}>
        {value.title}
        {value.content}
      </li>      
    ))
  }}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        {data ? 
          <div>
            {datas}
          </div>
        :
          <p>データがありません</p>
        }
      </main>
    </div>
  )
}

export default Home
