import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import List from './components/list'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import {useState} from 'react'

const fetcher = (...args: any) => fetch(...args).then(res => res.json())

const Home: NextPage = () => {
  {console.log("index.js")}
  const [ address, setAddress ] = useState('http://localhost:8080/')
  const { data, error } = useSWR(address, fetcher)
  {console.log(data)}
  {if(data){
    console.log("------------")
    console.log(data.length)
  }}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
      {data ? 
      <div>
      <p>{data[0].title}</p>
      <p>{data[0].content}</p>
      </div>

  :
      <p>"データがありません"</p>
  }
        {/* <List /> */}
      </main>
    </div>
  )
}

export default Home
