import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import List from './components/list'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import { useState, useEffect } from 'react'
import { title } from 'process'
import axios from 'axios'

const fetcher = (...args: any) => fetch(...args).then(res => res.json())

const Home: NextPage = () => {
  console.log("---------------------------------------topレベル")
  const [ address, setAddress ] = useState('http://localhost:8080/')
  let { data, error } = useSWR(address, fetcher)
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [te, setTe] = useState('faa');
  function faFA(){
    axios.get('http://localhost:8080')
  .then(function (response) {
    // console.log("fa start")
    // console.log(response.data);
    // data = response.data
    // data[0].title = "変更するfa"
    // console.log("fa end")
  })
  }
  // useEffect(() => {
  //   {console.log("呼ばれました")}
  // }, [data])
  let aa: any = []

  const send = async () => {
    setTitle("")
    setContent("")
    axios.post(`http://localhost:8080/register?title=${title}&content=${content}`)
    .then((ret)=>{
      setTe("fafafafa")
      console.log("----------------------ret")
      // console.log(JSON.stringify(ret.data))
      // console.log(data)
      // data[0]["ID"]
      data[0].title = "変更する"
      // data.splice(0)
      // // console.log(JSON.stringify(data))
      data = ret.data
      console.log(JSON.stringify(data))
      // aa.push(ret.data)
      // data.push({"title": "test", "content": "test"})
      // data = useSWR(address, fetcher)
      // console.log(JSON.stringify(data))
      // faFA()
    })
  };
  // if(data){
  //   console.log(JSON.stringify(data[0].title))
  // }

  let datas;
  if(data){
    {console.log("map")}
    {console.log("--------------------------" + JSON.stringify(data))}
    datas = data.map((value: any,key: any)=>(
      <ul>
        <h3>{value.ID}番</h3>
        タイトル
        <li>{value.title}</li>
        内容
        <li>{value.content}</li>   
      </ul>

    ))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
      <h1>投稿フォーム</h1>
        <label>タイトル:</label><br></br>
        <input type="text" name="title" value={title} onChange={(e) => setTitle(e.target.value)}/><br></br>
        <label>内容</label><br></br>
        <input type="text" name="content" value={content} onChange={(e) => setContent(e.target.value)}/><br></br>
        <button type="submit" onClick={send}>送信</button><br></br>
        {data ? 
          <div>
            {datas}
          </div>
        :
          <p></p>
        }
      </main>
    </div>
  )
}

export default Home